### ISSUE TITLE
any_char() ignores lo, hi arguments

### ISSUE THREAD

**Issue by UweBlock** [richierocks/rebus#2]
Thank you for the package. Just having started to use it for a project and found it very useful.
However, any_char() ignores the lo, hi arguments:
``` R
> any_char(0, Inf)
<regex> .
> any_char(1, 2)
<regex> .
> any_char(4)
<regex> .
# WORKAROUND:
> repeated(ANY_CHAR, 0, Inf)
<regex> .*
> repeated(ANY_CHAR, 1, 2)
<regex> .{1,2}
> repeated(ANY_CHAR, 4)
<regex> .{4}
```

Brgds,
Uwe

**Comment by richierocks** [comment]
Well spotted; thanks.  Now fixed in the development version.
